- name: Get a list of all libvirt guests
  community.libvirt.virt:
    command: list_vms
  register: libvirt_guests

- name: Display the list of all libvirt guests
  ansible.builtin.debug:
    var: libvirt_guests

- name: List all running vms
  community.libvirt.virt:
    command: list_vms
    state: running
  register: libvirt_running_vms

- name: Print list
  ansible.builtin.debug:
    var: libvirt_running_vms
