- name: List available networks
  community.libvirt.virt_net:
    command: list_nets
  register: libvirt_nets

- name: Print the list
  ansible.builtin.debug:
    var: libvirt_nets

- name: Get XML data of a specified network
  community.libvirt.virt_net:
    command: get_xml
    name: host-bridge
  register: libvirt_host_bridge_xml

- name: Print host-bridge network XML
  ansible.builtin.debug:
    var: libvirt_host_bridge_xml
