- name: Update CentOS (using package manager)
  ansible.builtin.package:
    name: '*'
    state: latest  # noqa: package-latest
  when: ansible_os_family == 'RedHat'

- name: Install a list of packages with a list variable
  ansible.builtin.package:
    name: "{{ common_packages }}"
    state: latest  # noqa: package-latest
  when: ansible_os_family == 'RedHat'

- name: Update Ubuntu (using apt)
  ansible.builtin.apt:
    only_upgrade: 'yes'
  when: ansible_os_family == 'Debian'
