- name: Allow ntp through firewall
  ansible.builtin.command:
    cmd: firewall-cmd --zone=public --add-port=123/udp --permanent
  register: common_fw_output
  changed_when: common_fw_output.rc != 0

- name: Reload firewall
  ansible.builtin.command:
    cmd: firewall-cmd --reload
  register: common_fw_reload
  changed_when: common_fw_reload.rc != 0
