---
- name: Check if osquery is installed
  ansible.builtin.command:
    cmd: dpkg-query -W osquery
  register: osquery_check_deb
  failed_when: osquery_check_deb.rc > 1
  changed_when: osquery_check_deb.rc == 1

- name: Download my_package
  ansible.builtin.get_url:
    url: "{{ osquery_dpkg_url }}"
    dest: "/tmp/osquery.deb"
    mode: '0440'
    checksum: "{{ osquery_dpkg_sha }}"
    validate_certs: true  # SECURITY: Ensure SSL/TLS certificates are validated
  when: osquery_check_deb.rc == 1

- name: Install OSQuery
  ansible.builtin.apt:
    deb: /tmp/osquery.deb
  when: osquery_check_deb.rc == 1
